# Python基础

## 变量和简单数据类型

In [1]:
print("Hello,world")

Hello,world


### 变量

In [2]:
message="Hello"
print(message)

Hello


### 字符串

In [3]:
name="John Smith"
print(name.title())
print(name.upper())
print(name.lower())

John Smith
JOHN SMITH
john smith


In [4]:
first_name="John"
last_name="Smith"
name=first_name+" "+last_name
print(name)

John Smith


In [5]:
print("Python命名规范：\n\t*只包含字母、数字和下划线\n\t*不能包含空格\n\t*不要使用关键字")

Python命名规范：
	*只包含字母、数字和下划线
	*不能包含空格
	*不要使用关键字


In [6]:
name = " john "
hello = "hello"
print(name.rstrip()+hello)
print(name.lstrip()+hello)
print(name.strip()+hello)

 johnhello
john hello
johnhello


### 数字

In [7]:
2+3

5

In [8]:
3-2

1

In [9]:
3/2

1.5

In [10]:
# 可能不准确
0.2+0.1

0.30000000000000004

类型转换

In [11]:
age=23
print("Happy "+str(age)+"rd Birthday")

Happy 23rd Birthday


### 注释

In [12]:
# 用#符号表示注释
print("#表示注释")

#表示注释


### Python 之禅

In [13]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## 列表

In [14]:
myhome=["sofa","computer","TV"]
print(myhome)
print(myhome[0])
print(myhome[1].title()+" is important.")

['sofa', 'computer', 'TV']
sofa
Computer is important.


### 方法

In [15]:
myhome[0]='router'
print(myhome)

['router', 'computer', 'TV']


In [16]:
myhome.append('camera')
print(myhome)

['router', 'computer', 'TV', 'camera']


In [17]:
myhome.insert(1,"laptop")
print(myhome)

['router', 'laptop', 'computer', 'TV', 'camera']


删除元素

In [18]:
del myhome[2]
print(myhome)

['router', 'laptop', 'TV', 'camera']


In [19]:
myhome.pop()
print(myhome)

['router', 'laptop', 'TV']


In [20]:
myhome.pop(1)
print(myhome)

['router', 'TV']


按值删除

In [21]:
time=["day","minite","second"]
time.remove("day")
print(time)

['minite', 'second']


### 组织列表

In [22]:
myhome.sort()
print(myhome)

['TV', 'router']


In [23]:
alphabet=['a','b','c','d','e']
alphabet.sort()
print(alphabet)
alphabet.sort(reverse=True)
print(alphabet)

['a', 'b', 'c', 'd', 'e']
['e', 'd', 'c', 'b', 'a']


临时排列

In [24]:
test=['3','a','e','r','b']
print(sorted(test))
print(test)

['3', 'a', 'b', 'e', 'r']
['3', 'a', 'e', 'r', 'b']


反转列表

In [25]:
test.reverse()
print(test)

['b', 'r', 'e', 'a', '3']


取得长度

In [26]:
print(len(test))

5


## 操作列表

### 遍历

In [27]:
magicians=['alice','david','carolina']
for magician in magicians:
    print(magician)

alice
david
carolina


### 注意缩进

In [28]:
for magician in magicians:
    print("Hello, "+magician.title())
print("Thank you!")

Hello, Alice
Hello, David
Hello, Carolina
Thank you!


:冒号表示循环
缩进表示循环语句

### 创建数值列表

In [29]:
for a in range(3,8):
    print(a)


3
4
5
6
7


In [30]:
# 将range转换为列表
print(list(range(5,9)))

[5, 6, 7, 8]


In [31]:
# **表示乘方
6**3

216

In [32]:
squares=[]
for value in range(1,11):
    squares.append(value**2)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [33]:
for i in range(0,10):
    print(squares[i])

1
4
9
16
25
36
49
64
81
100


In [34]:
# 找到最大值
print(max(squares))
# 找到最小值
print(min(squares))
# 求和
print(sum(squares))

100
1
385


### 切片

In [35]:
a=[]
for i in range(1,11):
    a.append(i**3)
print(a)
print(a[0:3])
print(a[:3])#自动从头开始
print(a[3:4])
print(a[-3:])#打印最后三个

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[1, 8, 27]
[1, 8, 27]
[64]
[512, 729, 1000]


复制列表

In [36]:
b=a # 不是复制，而是引用
print(b)
b[0]=0
print(a)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[0, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [37]:
b=a[:]# 正确的复制
b[0]=1
print(a)
print(b)

[0, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


**正确的复制方法：** list2=list1[:]

### 元组

不可变的列表为元组

In [38]:
dimensions=(6,9)
print(dimensions)

(6, 9)


元组同样可以遍历

In [39]:
for i in dimensions:
    print(i)

6
9


元组的元素不可改变，但变量可以重新赋值

In [40]:
a=(1,2,3)
#a[0]=1
#TypeError: 'tuple' object does not support item assignment
print(a)
a=(2,3,4)
print(a)

(1, 2, 3)
(2, 3, 4)


## if语句

In [41]:
name = "tom"
if name =="john":
    print("you are john".title())
else:
    print("you are not john".title())
        

You Are Not John


In [42]:
b=[1,6,8,4,5,7]
for i in b:
    if i>5:
        print(i)

6
8
7


判断符号有
- ==
- !=
- \>
- \>\=
- \<
- \<\=

In [43]:
3>2

True

逻辑判断
- and
- or

In [44]:
age=19
age<20 or age>30

True

检查值是否在列表中

In [45]:
numlist=[3,6,9]
3 in numlist

True

In [46]:
6 not in numlist

False

布尔表达式

In [47]:
Window_enable = True
print(str(not Window_enable))

False


多重判断

if

elif

else

In [48]:
age = 15
if age>=30:
    print("You are mid-aged.")
elif age>18:
    print("You are adult.")
elif age>14:
    print("You are teenager.")
else:
    print("You are so young.")

You are teenager.


  if 还可以判断列表是否为空

In [49]:
testlist=[]
if testlist:
    print("表非空")
else:
    print("表为空")

表为空


In [50]:
testlist=[1,2]
if testlist:
    print("表非空")
else:
    print("表为空")

表非空


In [56]:
user=input()
if user=="root":
    print("You UID is 0")
elif user.lower().strip() =="tom":
    print("You UID is 1000")
else:
    print("I don't know your UID")

Tom 
You UID is 1000


## 字典

### 创建字典

In [2]:
car_0={'color':'green','power':500} #好像json啊
print(car_0['power'])

500


**键-值**是两个相关联的值，可以通过键获得相关的值

### 使用字典

修改值

In [3]:
car_0={'color':'green','power':500}
car_0['color']='blue' #通过键来修改值
print(car_0)

{'color': 'blue', 'power': 500}


添加键-值对

In [5]:
car_1={} #定义一个空字典
car_1['color']='black' #添加键-值对
car_1['power']=300
print(car_1)

{'color': 'black', 'power': 300}


删除键-值对

In [6]:
car_0={'color':'green','power':500}
del car_0['power']
print(car_0)

{'color': 'green'}


多行写法

In [7]:
car_0={
    'color':'white',
    'power':460,
    'owner':'sarah',#可以写逗号
}
print(car_0)

{'color': 'white', 'power': 460, 'owner': 'sarah'}


### 遍历字典

In [10]:
car_0={
    'color':'white',
    'power':460,
    'owner':'sarah'
}
for key,value in car_0.items(): # items方法返回一个键-值对列表
    print(key+':'+str(value)+'\n')

color:white

power:460

owner:sarah



遍历所有键

In [12]:
for key in car_0.keys():
    print("key:"+key+'\n'+'Value:'+str(car_0[key])+'\n\n')

key:color
Value:white


key:power
Value:460


key:owner
Value:sarah




In [15]:
print(car_0.values())

dict_values(['white', 460, 'sarah'])


按顺序遍历所有键

In [20]:
for key in sorted(car_0.keys()):
    print("key:"+key+'\n'+'Value:'+str(car_0[key])+'\n\n')

key:color
Value:white


key:owner
Value:sarah


key:power
Value:460




遍历所有值

In [2]:
car_0={
    'color':'white',
    'power':460,
    'owner':'sarah'
}
for value in car_0.values():
    print(str(value))

white
460
sarah


In [3]:
name_age={
    'Tom':18,
    'John':19,
    'Sarah':18,
    'Jen':19,
    'Phil':20,
    'Edward':17,
}
for v in name_age.values():
    print(v)

18
19
18
19
20
17


可以看到输出中有许多重复的值

In [5]:
for v in set(name_age.values()): # 创建集合
    print(v)

17
18
19
20


通过集合创建独一无二的元素组

In [6]:
len(name_age) # 获得长度

6

### 嵌套

In [8]:
aliens = []
for i in range(0,30):
    if i%2==0:
        aliens.append({'color':'green','points':5,'speed':'slow'})
    else:
        aliens.append({'color':'yellow','points':10,'speed':'medium'})
for alien in aliens[:5]:
    print(alien)

{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'yellow', 'points': 10, 'speed': 'medium'}
{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'yellow', 'points': 10, 'speed': 'medium'}
{'color': 'green', 'points': 5, 'speed': 'slow'}


在字典中存储列表

In [9]:
pizza = {
    'crust':'thick',
    'toppings':['mushrooms','extra cheese'],
}#超级像Json

在字典中也可以存储字典

## 用户输入和while循环

### input()的工作原理

In [1]:
name=input("What's your name? Input: ")#参数为提示信息，注意在冒号后加一个空格
print('Hello,'+name)

What's your name? Input: Sarah
Hello,Sarah


输入一定为字符串，输入的数字需要转换

In [4]:
age=input('How old are you? ')
age=int(age)
if age<25:
    print('You are so young')

How old are you? 21
You are so young


In [ ]:
#也可以这么写
age=int(input('How old are you? '))
#python2.7使用raw_input()

### while循环

In [5]:
i=1
while i<=5:
    print(i)
    i+=1

1
2
3
4
5


使用标志

In [9]:
active = True
while active:
    if input("Input 'quit' to quit: ")=='quit':
        active = False
    else:
        print('MENU:\n\ta\n\tb\n\tblabla')
print("quit scussfully")

Input 'quit' to quit: no
MENU:
	a
	b
	blabla
Input 'quit' to quit: quit
quit scussfully


使用break

In [11]:
while True:
    if input("Input 'quit' to quit: ")=='quit':
        break
    else:
        print('MENU:\n\ta\n\tb\n\tblabla')
print("quit scussfully")

Input 'quit' to quit: no
MENU:
	a
	b
	blabla
Input 'quit' to quit: sorry
MENU:
	a
	b
	blabla
Input 'quit' to quit: quit
quit scussfully


使用continue

In [12]:
i=0
while i<10:
    i+=1
    if i%2==0:
        continue
    print(i)

1
3
5
7
9


### 使用while循环来处理列表和字典

移动元素

In [1]:
#验证用户
uu=['alice','brian','candace']
cu=[]
while uu:
    nu=uu.pop()
    print('验证'+nu.title()+'中')
    print('输入y通过验证')
    if input()=='y':
        cu.append(nu)

print('\n通过验证的用户:')
for u in cu:
    print('\t'+u.title())

验证Candace中
输入y通过验证
n
验证Brian中
输入y通过验证
y
验证Alice中
输入y通过验证
y

通过验证的用户:
	Brian
	Alice


从列表中删除所有特定值

In [2]:
list1=['a','c','v','a','a']
print(list1)

while 'a' in list1:
    list1.remove('a')
    
print(list1)

['a', 'c', 'v', 'a', 'a']
['c', 'v']


使用用户输入来填充字典

In [2]:
ans={}

while True:
    name=input("\n你的名字： ")
    likes=input("你喜欢什么: ")
    
    ans[name]=likes
    
    if input("是否还有其他受调查者？ (yes/no)")=='no':
        break

print("\n----调查结果----")
for name,likes in ans.items():
    print(name+"喜欢"+likes+"。")



你的名字： 汪灿
你喜欢什么: 健身
是否还有其他受调查者？ (yes/no)yes

你的名字： 胡润宇
你喜欢什么: LOL
是否还有其他受调查者？ (yes/no)no

----调查结果----
汪灿喜欢健身。
胡润宇喜欢LOL。


## 函数

### 定义函数

In [5]:
def print_hello(): #定义一个函数
    """这里写函数的使用方法"""
    print("Hello")

print_hello() #调用函数

Hello


In [7]:
def greet(name):#name为行参
    """显示简单的问候语"""
    print("Hello,"+name)

greet('Tom')#'Tom'为实参

Hello,Tom


### 传递实参

位置实参

In [12]:
def pow(n,i):
    re=1
    while i>0:
        re*=n
        i-=1
    print(re)

pow(3,5)

243


关键字实参

In [14]:
def description(name,age):
    print(name.title()+' is '+str(age)+' years old.')

description('Tom',20)
description(age=22,name='sarah')#关键字实参

Tom is 20 years old.
Sarah is 22 years old.


In [16]:
def describe_pet(name,type='dog'):#设定type的默认值为dog
    """显示宠物的信息"""
    print('I have a '+type+'.')
    print('My '+type+"'s name is "+name.title())
describe_pet(name='willie')
describe_pet('jelly')

I have a dog.
My dog's name is Willie
I have a dog.
My dog's name is Jelly


### 返回值

In [17]:
def strcat(str1,str2):
    return str1+str2#使用return返回值

print(strcat("Hello,","World!"))

Hello,World!


让参数变成可选

In [1]:
def get_formatted_name(first,last,middle=''):
    if middle:
        full_name=first+' '+middle+' '+last
    else:
        full_name=first+' '+last
    return full_name.title()

### 传递列表

In [2]:
def greet_users(names):
    for name in names:
        print("Hello, "+name.title()+"!")

usernames=['hannah','ty','margot']
greet_users(usernames)

Hello, Hannah!
Hello, Ty!
Hello, Margot!


函数中可以修改列表

In [7]:
def move_list(sou,des):
    des.append(sou.pop())

a=[1,2,3]
b=[]
move_list(a,b)
print(a)
print(b)

[1, 2]
[3]


禁止函数修改列表

In [8]:
def move_list(sou,des):
    des.append(sou.pop())

a=[1,2,3]
b=[]
move_list(a[:],b[:])#通过切片阻止修改
print(a)
print(b)

[1, 2, 3]
[]


### 传递任意数量实参

In [9]:
def foo(*para):#创建元组
    print(para)

foo('Hello','World','!')

('Hello', 'World', '!')


\*使python创建一个元组，并将参数存入

接受任意数量位置参数

In [8]:
def printf(str1,*rep):
    """将字符串中的{0},{1}等依次替换"""
    for i in range(0,len(rep)):
        str1=str1.replace('{'+str(i)+'}',str(rep[i]))
    print(str1)

printf("你好,我是{0}，年龄为{1}","tom",21)

你好,我是tom，年龄为21


接受任意数量关键字参数

In [10]:
def print_message(name,**info):#创建字典
    message=info
    message['name']=name
    print(message)

print_message('Tom',age=18, location='武汉')


{'age': 18, 'location': '武汉', 'name': 'Tom'}


### 将函数存储在模块中

In [12]:
import numpy as np #直接导入模块
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
sum = a + b 
difference = a - b 
product = a * b 
quotient = a / b 
print ("Sum = \n", sum)
print ("Difference = \n", difference )
print ("Product = \n", product )
print ("Quotient = \n", quotient )

Sum = 
 [[ 6.  8.]
 [10. 12.]]
Difference = 
 [[-4. -4.]
 [-4. -4.]]
Product = 
 [[ 5. 12.]
 [21. 32.]]
Quotient = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
from numpy.random import randn,random #导入模块中特定函数
i=randn()
print(i)
random((5))

-0.32438948036570586


array([0.66795368, 0.771075  , 0.42334449, 0.18891722, 0.21044395])

设置别名

In [5]:
from numpy.random import randn as rn
rn()

0.6253118013738759

导入所有函数

In [ ]:
from numpy.random import *

最好不要使用这种方式

## 类

面向对象编程

### 创建类

In [7]:
class Dog():
    """一次模拟小狗的尝试"""
    
    def __init__(self,name,age): #创建实例时自动运行，自动传入指向实例本身的引用self
        """初始化name和age"""    #调用只需两个参数
        self.name=name
        self.age=age
    
    def sit(self):
        print(self.name.title()+" is sitting")
    
    def roll(self):
        print(self.name.title()+" rolled over! ")

**创建实例**

In [8]:
my_dog=Dog('willie',6)

print(my_dog.name)
print(str(my_dog.age))

my_dog.sit()

willie
6
Willie is sitting


### 使用类和实例

In [3]:
class Car():
    """Just try"""
    
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
    
    def get_descriptive_name(self):
        long_name=str(self.year)+' '+self.make+" "+self.model
        return long_name.title()
    
my_new_car=Car('audi','a4',2016)
print(my_new_car.get_descriptive_name())

2016 Audi A4


设置属性的默认值
在 `__init__()` 中设置`self.member=value` 

修改属性的值
1. 直接修改
2. 通过方法

In [4]:
my_new_car.year=2017 #通过.来修改
print(my_new_car.get_descriptive_name())

2017 Audi A4


In [6]:
class Car():
    """Just try"""
    
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
    
    def get_descriptive_name(self):
        long_name=str(self.year)+' '+self.make+" "+self.model
        return long_name.title()
    
    def set_year(self,year): #修改属性的函数
        self.year=year

my_new_car=Car('audi','a4',2016)
print(my_new_car.get_descriptive_name())
my_new_car.set_year(2018) #调用修改属性的方法
print(my_new_car.get_descriptive_name())

2016 Audi A4
2018 Audi A4


 ### 继承

In [19]:
class Car():
    """Just try"""
    
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
        self.odometer_reading=0
    
    def get_descriptive_name(self):
        long_name=str(self.year)+' '+self.make+" "+self.model
        return long_name.title()
    
    def read_odometer(self):
        print('This car has '+str(self.odometer_reading)+ "miles on it.")
    
    def update_odometer(self, mileage):
        if mileage >=self.odometer_reading:
            self.odometer_reading = mileage
        else:
            print("You can't roll back an odometer!")
    
    def increment_odometer(self, miles):
        self.odometer_reading += miles

class ElectricCar(Car): #将父类填到括号中来继承
    
    def __init__(self, make, model, year):
        self.battery_size = 40
        super().__init__(make, model,year)
        
        
    def describe_battery(self):
        print("This car has a "+str(self.battery_size) +"kWh battery.")
    
my_tesla=ElectricCar('tesla','model s', 2016)
print(my_tesla.get_descriptive_name())
my_tesla.describe_battery()

2016 Tesla Model S
This car has a 40kWh battery.


**重写父类方法**

In [30]:
class ElectricCar(Car): 
    
    def __init__(self, make, model, year):
        self.battery_size = 70
        super().__init__(make, model,year)
        
        
    def describe_battery(self):
        print("This car has a "+str(self.battery_size) +"kWh battery.")
        
    def get_descriptive_name(self): #重写父类的方法
       
        return super().get_descriptive_name()+" with "+str(self.battery_size)+"kWh battery" #这里调用了父类的方法
    
my_tesla=ElectricCar('tesla','model s', 2016)
print(my_tesla.get_descriptive_name())

2016 Tesla Model S with 70kWh battery


### 导入类

In [4]:
from numpy import array
a=array([[1,2],[3,4]])
print(a)
print(type(a)) 
print(a.dtype)
print(a.size) 
print(a.shape) 
print(a.itemsize)
print(a.ndim) 
print(a.nbytes)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
int32
4
(2, 2)
4
2
16


**其他导入方法**

In [11]:
from numpy import array, matrix #引入多个类

In [13]:
import numpy #直接引入模块

### Python 标准库

python标准库时一组模组

### 类编码风格

类名采用**驼峰命名法**，即首字母大写，不用下划线
实例名和模块名都用小写，并加上下划线
每个类都要用文档字符串

## 文件操作

### 从文件中读取数据

In [1]:
with open('pi_digits.txt') as file_object:
    contents = file_object.read()
    print(contents)

3.1415926535
  8979323846
  2643383279



用open()打开文件才能访问
with在不需要访问时将其关闭
也可以使用close()

最后一行是空的，这是文件末尾

In [1]:
with open('pi_digits.txt') as file_object:
    contents = file_object.read()
    print(contents.rstrip()) # 去除空行

3.1415926535
  8979323846
  2643383279


In [3]:
with open('/home/tom/.bashrc') as bashrc: # 使用绝对路劲
    contents=bashrc.read()
    print(contents)
# windows_path='C:\Users\asdfz\.bashrc'

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ps='busybox ps'
alias grep='grep --color'
# PS1='[\u@\h \W]\$ '
PS1='\[\e]0;\u@\h: \w\a\]\[\033\]\u@\h\[\033\]:\[\033\]\w \$\[\033\] '

export $(dbus-launch)
export EDITOR="/usr/bin/vim"
export QT_AUTO_SCREEN_SCALE_FACTOR="0"
export XDG_RUNTIME_DIR="/run/user/1000"



**逐行读取**

In [9]:
filename='pi_digits.txt'

with open(filename) as file_object:
    for line in file_object:
        print(line)

3.1415926535

  8979323846

  2643383279



由于每行末尾有换行符，print自动添加换行符，因此有空行

**创建列表**

In [10]:
with open(filename) as file_object:
    lines=file_object.readlines()

print(lines)

['3.1415926535\n', '  8979323846\n', '  2643383279\n']


In [17]:
pi_str=''
for line in lines:
    pi_str+=line.strip()

print(pi_str)
print(len(pi_str))
pi=float(pi_str)#转换为浮点数
pi+=pi
print(pi)

3.141592653589793238462643383279
32
6.283185307179586


### 写入文件

In [2]:
#写入空文件
filename = 'out.txt'
with open(filename,'w') as file_object:
    file_object.write("I love programming.") #只接受字符串，且不会自动添加换行符
    file_object.write("\nI love creating new games.")

open的第二个参数
- 'r'读取模式
- 'w'写入模式
- 'a'附加模式
- 'r+'读写模式
默认为只读模式
使用'w'时请小心，因为会覆盖文件

In [3]:
# coding=utf-8
with open(filename,'a') as file_object:
    file_object.write("\n")
    file_object.write("-----attch text-----\n")

### 分析文本

In [7]:
#with open("1342-0.txt") as file_object:
#    contents = file_obj.read()

from urllib import request

file_path = "http://www.gutenberg.org/files/1342/1342-0.txt"
contents = request.urlopen(file_path).read().decode('utf8')

words = contents.split()
num_words = len(words)
print("The book Pride and Prejudice has "+str(num_words) + " words. ")

The book Pride and Prejudice has 124592 words. 


### 存储数据

使用**JSON**来保存数据是常见的方式

In [11]:
import json

data={'name':'tom','age':18,'pos':[66,51]}
filename = 'num.json'
with open(filename,'w') as f_obj:
    json.dump(data,f_obj) #写入json文件

with open(filename) as f_r:
    r_data=json.load(f_r) #读取json文件

print(r_data)

{'name': 'tom', 'age': 18, 'pos': [66, 51]}


In [3]:
import json

def get_stored_username():
    """获取存储的用户名"""
    filename='data/username.json'
    try:
        with open(filename) as fobj:
            username = json.load(fobj)
    except FileNotFoundError:
        return None
    else:
        return username

def greet_user():
    """问候用户"""
    username = get_stored_username()
    if username:
        print("Welcome back, "+ username + "! ")
    else:
        username = input("What is your name? ")
        with open('data/username.json','w') as fobj:
            json.dump(username,fobj)
            print("We'll remember you when you come back, " + username + "! ")
            
greet_user()

What is your name? Tom
We'll remember you when you come back, Tom! 


## 异常

发生错误时会创建异常对象，如果没有进行处理，程序将停止，并显示一个traceback。
处理异常的方式是try-except

**ZeroDivisionError**

In [12]:
print(5/0)

ZeroDivisionError: division by zero

In [14]:
try:
    print(5/0)
except ZeroDivisionError:
    print("Error:You can't divide by zero! ")

Error:You can't divide by zero! 


In [26]:
try:
    first_number=int(input("\nFirst number: "))
    second_number=int(input("\nSecond number: "))
except ValueError:
    print('Please input numbers! ')

else:
    try:
        aswser=first_number/second_number
    except ZeroDivisionError:
        print("You can't divide by 0!")

    else: #如果try成功执行，则会执行else中的代码
        print(answer)


First number: 2

Second number: 0
You can't divide by 0!


**FileNotFoundError**

In [27]:
filename='hello.txt'

try:
    with open(filename) as f_obj:
        contents=f_obj.read()
except FileNotFoundError:
    print('File not exist! ')

File not exist! 


### 在失败时一声不吭

In [6]:
try:
    with open('hello.txt') as hello:
        contents=hello.read()
except FileNotFoundError:
    pass #直接什么都不做
else:
    print("命令成功执行")
print('完成')

完成


## 测试代码

### 测试函数

Python标准库中的模块unittest提供了代码测试工具。

**单元测试**用于核实函数的某个方面没问题。

**测试用例**是一组单元测试

**全覆盖式测试**包含一整套单元测试，包含各种可能的函数使用方式

In [ ]:
import unittest

def get_formatted_name(first,last): #待测试的函数 也可以通过from * import fun_name的方式引入
    full_name = first +' ' + last
    return full_name.title()

class NamesTestCase(unittest.TestCase): #可以随便取名字，但必须继承unittest.TestCase
    """测试函数"""
    
    def test_first_last_name(self): #测试时，所有test_开头的函数会自动运行
        formatted_name = get_formatted_name('janis','joplin')
        self.assertEqual(formatted_name,'Janis Joplin') #断言方法，进行判断

unittest.main() #jupyter平台无法运行
#结果为：
#.
#----------------------------------------------------------------------
#Ran 1 test in 0.000s
#
#OK

进行两个测试

In [ ]:
import unittest

def get_formatted_name(first,last,middle=''): #待测试的函数 也可以通过from * import fun_name的方式引入
    if middle:
        full_name=first+' '+middle + ' '+ last
    else:
        full_name = first +' ' + last
    return full_name.title()

class NamesTestCase(unittest.TestCase): #可以随便取名字，但必须继承unittest.TestCase
    """测试函数"""
    
    def test_first_last_name(self): #测试时，所有test_开头的函数会自动运行
        formatted_name = get_formatted_name('janis','joplin')
        self.assertEqual(formatted_name,'Janis Joplin') #断言方法，进行判断
    
    def test_first_last_middle_name(self):
        formatted_name = get_formatted_name('wolfgang','mozart','amadeus')
        self.assertEqual(formatted_name,'Wolfgang Amadeus Mozart')

unittest.main()

### 测试类

断言方法

|方法|用途
|---|---|
|assertEqual(a,b)|核实a==b|
|assertNotEqual(a,b)|核实a!=b|
|assertTrue(x)|核实x为True|
|assertFalse(x)|核实x为False|
|assertIn(item,list)|核实item在list中|
|assertNotIn(item,list)|核实item不在list中|